name: branching name test

on: 
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: get Ram details
        run: |
           free -m
           # echo "hello world"
           echo "good"

      - name: get Ram details
        run: free -h --si

      - name: get Ram details
        run: grep MemTotal /proc/meminfo

      
