name: branching name test

on: 
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: get Ram details
        run: free -m

      - name: get Ram details
        run: free -h --si
