name: Set Secrets
on:
  workflow_call:
    outputs:
      spn_credentials:
        value: ${{ jobs.spn.outputs.spn_credentials }}

jobs:
 spn:
  runs-on: ubuntu-latest
  outputs:
    spn_credentials: ${{ steps.spn.outputs.spn_credentials }}

  steps:
    - name: spnn
      run: |
        echo "client_id=c4594805-58e6-4759-b25a-572fa1cce446" >> $GITHUB_OUTPUT
        echo "client_secret=geX8Q~NiM5xVuw6dzTW3~eCqfYU2LG_xbU1zfaPt" >> $GITHUB_OUTPUT
        echo '{"client_id": "c4594805-58e6-4759-b25a-572fa1cce446", "client_secret": "geX8Q~NiM5xVuw6dzTW3~eCqfYU2LG_xbU1zfaPt"}' >> client_credentials.json

    - name: set output
      id: spn
      run: |
        echo "spn_credentials=$(cat client_credentials.json)" >> $GITHUB_OUTPUT
