
name: Call secret workflow

on:
  workflow_dispatch:


jobs:
  spn:
    uses: ./.github/workflows/calledsecretworkflow2.yml
    secrets: inherit

  Print:
    runs-on: ubuntu-latest
    needs: spn

    env: 
      spn_credentials: ${{ needs.spn.outputs.spn_credentials }}
    
    steps:
    - name: print details
      run: |
        echo ${{ env.spn_credentials }}
