name: Sub 2 numbers

on:
  workflow_call:
    inputs:
      numA:
        required: true
        type: number
      numB:
        required: true
        type: number
    outputs:
      total:
        value: ${{ jobs.Sub.outputs.sub_total }}

env: 
    NUMBER_A: ${{ inputs.numA }}
    NUMBER_B: ${{ inputs.numB }}

jobs:
 Sub:
  runs-on: ubuntu-latest



  steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: display
      run: echo ${{ github.event_name }}

    - name: Sub of 2 numbers
      id: sub
      run: |
        import os
        Total=${{ env.NUMBER_A }} - ${{ env.NUMBER_B }}
        print(f"Sub of 2 numbers is : {Total}")
        with open(os.getenv('GITHUB_OUTPUT'),'a') as env_file:
          env_file.write(f'TOTAL={Total}\n')
      shell: python

  outputs:
    sub_total: ${{ steps.sub.outputs.TOTAL }}



        
