name: Call Addition and Sub of 2 numbers

on:
  workflow_dispatch:
    inputs:
      numA:
        required: true
        type: string
      numB:
        required: true
        type: string
      numC:
        required: true
        type: string

jobs:
  Addition:
    uses: Sushanth004/Sample/.github/workflows/calledaddition.yml@main
    secrets: inherit
    with:
      numA: 2
      numB: 4
