name: Call Addition and Sub of 2 numbers

on:
  workflow_dispatch:
    inputs:
      numA:
        required: true
        type: number
      numB:
        required: true
        type: number
      numC:
        required: true
        type: number

jobs:
  Addition:
    uses: ./.github/workflows/calledaddition.yml
    secrets: inherit
    with:
      numA: ${{ fromJson(github.event.inputs.numA) }}
      numB: ${{ fromJson(github.event.inputs.numB) }}

  Sub:
    uses: ./.github/workflows/calledsubstraction.yml
    secrets: inherit
    needs: Addition
    with:
      numA: ${{ fromJson(needs.Addition.outputs.total) }}
      numB: ${{ fromJson(github.event.inputs.numC) }}
