
name: Call secret workflow

on:
  workflow_dispatch:


jobs:
  spn:
    uses: ./.github/workflows/calledsecretworkflow.yml
    secrets: inherit

  Print:
    runs-on: ubuntu-latest
    needs: spn

    env: 
      client_id: ${{ needs.spn.outputs.client_id }}
      client_secret: ${{ needs.spn.outputs.client_secret }}
    
    steps:
    - name: print details
      run: |
        echo ${{ env.client_id }}
        echo ${{ env.client_secret }}
