name: checkout

on: 
  workflow_dispatch

jobs:
  build-push:
    runs-on: windows-2019
    steps:
      - name: checkout
        run: |
          git clone \
            --depth=1 \
            --filter=blob:none \
            --sparse \
            --single-branch \
            -b "test123456" \
            "https://github.com/Sushanth004/Sample.git" test_branch

      
