name: Conditional Job Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    # outputs:
    #   condition_met: ${{ steps.step1.outputs.condition_met }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some script
        id: step1
        run: |
            echo "::set-output name=condition_met::true"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    # if: needs.job1.outputs.condition_met == 'true'
    if: needs.job1.steps.step1.output.condition_met == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run conditional job
        run: echo "Job2 is running because the condition was met!"
