name: env

on:
  workflow_dispatch:
    inputs:
      ENV_TYPE:
        type: choice
        description: Deployment environment
        required: true
        options: 
          - Prod
          - Dev

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some script
        run: |
          if ${{ github.event.inputs.ENV_TYPE != 'Prod' }} ; then
              echo "ENVIRON=Prod" >> $GITHUB_ENV
          else
              echo "ENVIRON=NonProd" >> $GITHUB_ENV
          fi

      - name: Print
        run: |
          echo ${{ env.ENVIRON }}

