name: json

on: 
  workflow_dispatch:
    inputs:
      json_input:
        description: ''
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: set env 
        run: |
           import json
           import os
           json_str=json.loads(${{ github.event.inputs.json_input }})
           with open(os.getenv('GITHUB_ENV'), 'a') as env_file:
                  env_file.write(f'NAME={json_str["name"]}\n')
                  env_file.write(f'ID={json_str["id"]}\n')
           print(json_str)
        shell: python

      - name: get env 
        run: |
          import os
          print(os.getenv("NAME"))
          print(os.getenv("ID"))
        shell: python

