name: json

on: 
  workflow_dispatch:
    inputs:
      json_input:
        description: ''
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: set env 
        run: |
           import json
           import os
           json_str=json.loads(${{ github.event.inputs.json_input }})
           os.environ[json_str["name"]]="Sushanth"
           os.environ[json_str["id"]]="4"
           print(json_str)
        shell: python

      - name: get env 
        run: |
           echo "$name"
           echo "$id"

