name: json

on: 
  workflow_dispatch:
    inputs:
      json_input:
        description: ''
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: set env 
        run: |
           import json
           import os
           json_str=json.loads(${{ github.event.inputs.json_input }})
           print(json_str["name"])
           print(json_str["id"])
           os.environ["name"]=json_str["name"]
           os.environ["id"]=json_str["id"]
           print(json_str)
        shell: python

      - name: get env 
        run: |
          import os
          print(os.getenv("name"))
          print(os.getenv("id"))
        shell: python

