name: Get Details workflow
on: 
  workflow_dispatch:
  
jobs:
  test_job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: python code
        run: |
          from sample import ui_repo_map
          print(ui_repo_map['test])
        working-directory: common-utils
        shell: python
