name: First_Workflow
on:
  workflow_dispatch:
  
jobs:
  First_Job:
    name: FirstJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install xmllint
        run: |
          sudo apt-get install -y libxml2-utils
      - name: Print value
        run: |
            value=$(xmllint --html --xpath "string(/html/body/div/div[1]/table/tbody/tr/td[2]/div/div])" index.html)
            echo "$value"
      # - name: Read test results from index.html
      #   run: |
      #     if xmllint --html --xpath "string(//*[@id="successRate"])" index.html 2>/dev/null | grep -q "Fail"; then
      #       echo "Some tests have failed."
      #       xmllint --html --xpath "string(//*[@id="successRate"])" index.html 2>/dev/null
      #       exit 1
      #     else
      #       echo "All tests passed."
      #       xmllint --html --xpath "string(//*[@id="successRate"])" index.html 2>/dev/null
      #     fi
