name: First_Workflow
on:
  workflow_dispatch:
    inputs:
      myInput:
        default: "2024.1.1.0"
jobs:
  First_Job:
    name: FirstJob
    runs-on: ubuntu-latest
    steps:
      - name: Update value
        run: |
          version=${{ github.event.inputs.myInput }}
          #echo ${version//./_}
          echo "project_version=$(echo ${version//./_})" >> $GITHUB_ENV
      - name: output
        run: |
          echo "Version is ${{ env.project_version }} only"
