name: First_Workflow
on: workflow_dispatch
jobs:
  First_Job:
    name: FirstJob
    runs-on: ubuntu-latest
    steps:
      - name: copy files
        uses: actions/checkout@v3
      - name: run python file
        run: python helloworld.py
      - name: ls
        run: ls
