name: Set Secrets
on:
  workflow_call:
    outputs:
      client_id:
        value: ${{ jobs.spn.outputs.client_id }}
      client_secret:
        value: ${{ jobs.spn.outputs.client_secret }}

jobs:
 spn:
  runs-on: ubuntu-latest
  outputs:
    client_id: ${{ steps.spn.outputs.client_id }}
    client_secret: ${{ steps.spn.outputs.client_secret }}

  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: spn
      id: spn
      run: |
        python3 outputs.py
      working-directory: ${{ github.workspace }}
