name: Set Secrets
on:
  workflow_call:
    outputs:
      client_id:
        value: ${{ jobs.spn.outputs.client_id }}
      client_secret:
        value: ${{ jobs.spn.outputs.client_secret }}

jobs:
 spn:
  runs-on: ubuntu-latest
  outputs:
    client_id: ${{ steps.spn.outputs.client_id }}
    client_secret: ${{ steps.spn.outputs.client_secret }}

  steps:
    - name: spn
      id: spn
      run: |
        with open(os.getenv('GITHUB_OUTPUT','a') as env_file:
          env_file.write(f'client_id='c4594805-58e6-4759-b25a-572fa1cce446\n')
          env_file.write(f'client_secret='geX8Q~NiM5xVuw6dzTW3~eCqfYU2LG_xbU1zfaPt\n')
      shell: python
