name: Test workflow
on: 
  workflow_dispatch:
  
jobs:
  test_job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: configure config
        run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          
      - name: checkout monorepo tf env config files
        uses: actions/checkout@v4
        with:
          repository: Sushanth004/Test
          ref: main
          token: "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"
