name: Test workflow
on: 
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
jobs:
  test_job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: python version
        run: python --version
      - name: print
        run: echo "${{ toJSON(github.repository_owner) }}"