name: Test workflow
on: 
  workflow_dispatch:
  
jobs:
  test_job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: checkout monorepo tf env config files
        uses: actions/checkout@v4
        with:
          repository: learnings004/sample
          ref: main
          token: ${{ secrets.pat_token }}
