name: Conditional Job Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Version
        run: |
          echo "Hello"
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix: 
        version: [12, 14, 16]
        exclude:
         - version: 12
    steps:
      - name: Print Version
        run: |
          echo ${{ matrix.version }}

